fn main() {
    // To create a variable in Rust, use the let keyword and specify the name of the variable.
    let sex = "M";
    let age = 19;
    let name = "Dominik";
    let surname = "Waldburger";

    println!("{} {} is a {} year old {}", name, surname, age, sex);

    // {} are used as placeholders for values in the println! macro. A macro is like a function, but it works a bit differently.
    // The values to be printed are provided as additional arguments to the println! macro, in the order they should appear. <-- generated by AI


    let x = 5;
    //x = 10; // This line will cause a compile-time error because variables are immutable by default in Rust.
    println!("{}", x); // Apparently, I have to use quotation marks and add the variable after. 

    // If I want to change the value of a variable, I must use the mut keyword.

    let mut y = 10;
    println!("Before: {}", y);
    y = 15;
    println!("After: {}", y);

}